export default ['Arial',
  'Bahnschrift',
  'Calibri',
  'Cambria',
  'Cambria Math',
  'Candara',
  'Comic Sans MS',
  'Consolas',
  'Constantia',
  'Corbel',
  'Courier New',
  'Ebrima',
  'Franklin Gothic',
  'Gabriola',
  'Gadugi',
  'Georgia',
  'Impact',
  'Ink Free',
  'Javanese Text',
  'Leelawadee UI',
  'Lucida Console',
  'Lucida Sans Unicode',
  'Malgun Gothic',
  'Microsoft Himalaya',
  'Microsoft JhengHei',
  'Microsoft JhengHei UI',
  'Microsoft New Tai Lue',
  'Microsoft PhagsPa',
  'Microsoft Sans Serif',
  'Microsoft Tai Le',
  'Microsoft YaHei',
  '微软雅黑',
  'Microsoft YaHei UI',
  'Microsoft Yi Baiti',
  'MingLiU-ExtB',
  'PMingLiU-ExtB',
  'MingLiU_HKSCS-ExtB',
  'Mongolian Baiti',
  'MS Gothic',
  'MS UI Gothic',
  'MS PGothic',
  'MV Boli',
  'Myanmar Text',
  'Nirmala UI',
  'Palatino Linotype',
  'Segoe MDL2 Assets',
  'Segoe Print',
  'Segoe Script',
  'Segoe UI',
  'Segoe UI Emoji',
  'Segoe UI Historic',
  'Segoe UI Symbol',
  'SimSun',
  '宋体',
  'NSimSun',
  '新宋体',
  'SimSun-ExtB',
  'Sitka Small',
  'Sitka Text',
  'Sitka Subheading',
  'Sitka Heading',
  'Sitka Display',
  'Sitka Banner',
  'Sylfaen',
  'Symbol',
  'Tahoma',
  'Times New Roman',
  'Trebuchet MS',
  'Verdana',
  'Webdings',
  'Wingdings',
  'Yu Gothic',
  'Yu Gothic UI',
  'DengXian',
  '等线',
  'FangSong',
  '仿宋',
  'KaiTi',
  '楷体',
  'SimHei',
  '黑体',
  'HoloLens MDL2 Assets',
  'Book Antiqua',
  'Bookman Old Style',
  'Bookshelf Symbol 7',
  'Century',
  'Dubai',
  'FZShuTi',
  '方正舒体',
  'FZYaoTi',
  '方正姚体',
  'Garamond',
  'Century Gothic',
  'Leelawadee',
  'Microsoft Uighur',
  'Monotype Corsiva',
  'MT Extra',
  'MS Reference Sans Serif',
  'MS Reference Specialty',
  'LiSu',
  '隶书',
  'YouYuan',
  '幼圆',
  'STCaiyun',
  '华文彩云',
  'STFangsong',
  '华文仿宋',
  'STHupo',
  '华文琥珀',
  'STKaiti',
  '华文楷体',
  'STLiti',
  '华文隶书',
  'STSong',
  '华文宋体',
  'STXihei',
  '华文细黑',
  'STXingkai',
  '华文行楷',
  'STXinwei',
  '华文新魏',
  'STZhongsong',
  '华文中宋',
  'Wingdings 2',
  'Wingdings 3',
  'DejaVu Sans Mono',
  'Buxton Sketch',
  'Segoe Marker',
  'SketchFlow Print',
  'Microsoft MHei',
  'Microsoft NeoGothic',
  'Segoe WP',
  'Segoe WP SemiLight',
  'Marlett',
  'Global User Interface',
  'Global Monospace',
  'Global Sans Serif',
  'Global Serif']
