const assetsData = {
  dataItems: [],
  dataSet: [],
  dataStandard: [],
  dataIndex: [],
  report: [],
  file: [],
}
for (let i = 0; i < 100; i++) {
  assetsData.dataItems.push({
    id: 'dataItems' + i,
    name: 'TradeCode' + i + '（中文名称）',
    type: i % 2 === 0 ? 'int' : 'varchar',
    standard: '风险评估答案编号' + i,
    tags: 'skala, dataServer',
    remark: '备注内容',
  })
  assetsData.dataSet.push({
    id: 'dataSet' + i,
    name: 'TradeCode' + i + '（指标中文名称）',
    system: '机构管理' + i,
    dataSource: 'test-lsh-0602-' + i,
    createTime: '2022-06-01 19:04',
  })
  assetsData.dataStandard.push({
    id: 'dataStandard' + i,
    name: 'TradeCode' + i + '（标准中文名称）',
    code: 'SYKJ20220630099' + i,
    theme: 'isDeleted' + i,
    department: '财务管理部',
  })
  assetsData.dataIndex.push({
    id: 'dataIndex' + i,
    name: 'TradeCode' + i + '（指标中文名称）',
    code: 'ZB202206080100' + i,
    measure: '厘米' + i,
    type: 'basic',
  })
  assetsData.report.push({
    id: 'report' + i,
    name: 'TradeCode' + i + '（报表中文名称）',
    code: 'RP_0000497' + i,
    type: i % 2 === 0 ? '报表' : '多维分析',
    director: 'syx',
    createTime: '2022-06-01 19:04',
  })
  assetsData.file.push({
    id: 'file' + i,
    name: 'TradeCode' + i + '（文件中文名称）',
    type: i % 2 === 0 ? 'LIC' : 'PGN',
    size: '4M',
    createTime: '2022-06-01 19:04',
  })
}
export default {
  directory: [
    {
      englishName: '',
      extendProp: {},
      name: '域',
      type: 'domain',
      id: 1,
      level: 1,
      label: '域',
      parentId: 0,
      catalogName: '业务域',
      assetTypes: [],
      children: [
        {
          extendProp: {},
          englishName: '',
          name: '主题目录',
          type: 'theme',
          id: 2,
          level: 2,
          parentId: 1,
          catalogName: '主题',
          assetTypes: [],
          children: [
            {
              extendProp: {},
              englishName: '',
              name: '逻辑数据集',
              type: 'dataSet',
              id: 3,
              level: 3,
              parentId: 2,
              catalogName: '逻辑数据集',
              assetTypes: [
                {
                  name: '数据项',
                  code: 'dataItems',
                },
              ],
            },
            {
              extendProp: {},
              englishName: '',
              name: '业务场景',
              type: 'business',
              id: 4,
              level: 3,
              parentId: 2,
              catalogName: '业务场景',
              assetTypes: [
                {
                  name: '数据项',
                  code: 'dataItems',
                },
                {
                  name: '数据集',
                  code: 'dataSet',
                },
                {
                  name: '数据标准',
                  code: 'dataStandard',
                },
                {
                  name: '指标',
                  code: 'dataIndex',
                },
                {
                  name: '报表',
                  code: 'report',
                },
                {
                  name: '文件',
                  code: 'file',
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  tableOptions: [
    {
      label: '表1',
      value: 'table1',
    },
    {
      label: '表2',
      value: 'table2',
    },
    {
      label: '表3',
      value: 'table3',
    },
  ],
  securityLevelList: [
    {
      tagId: 83,
      name: 'L2-内部公开',
      builtIn: true,
      builtInCode: 'dataAuthA2',
      category: false,
      parentId: 81,
      parentName: '数据安全等级',
      properties:
        '{"builtInCode":"dataAuthA2", "description":"组织内部可以公开的数据", "css:background-color":"#e2f07c"}',
      order: null,
      catalogId: null,
      associatedTags: null,
      tagGroupId: null,
    },
    {
      tagId: 105,
      name: '1',
      builtIn: true,
      builtInCode: 'dataAuthA6',
      category: false,
      parentId: 81,
      parentName: '数据安全等级',
      properties: '{"builtInCode":"dataAuthA6","description":""}',
      order: null,
      catalogId: null,
      associatedTags: null,
      tagGroupId: 1,
    },
    {
      tagId: 81,
      name: '数据安全等级',
      builtIn: true,
      builtInCode: 'dataAuth',
      category: true,
      parentId: null,
      parentName: null,
      properties: '{"builtInCode":"dataAuth"}',
      order: null,
      catalogId: null,
      associatedTags: null,
      tagGroupId: 1,
    },
    {
      tagId: 108,
      name: '5',
      builtIn: true,
      builtInCode: 'dataAuthA9',
      category: false,
      parentId: 81,
      parentName: '数据安全等级',
      properties: '{"builtInCode":"dataAuthA9","description":""}',
      order: null,
      catalogId: null,
      associatedTags: null,
      tagGroupId: 1,
    },
    {
      tagId: 82,
      name: 'L1-外部公开',
      builtIn: true,
      builtInCode: 'dataAuthA1',
      category: false,
      parentId: 81,
      parentName: '数据安全等级',
      properties:
        '{"builtInCode":"dataAuthA1", "description":"需要向公众公开的数据", "css:background-color":"#7bd37c"}',
      order: null,
      catalogId: null,
      associatedTags: null,
      tagGroupId: null,
    },
    {
      tagId: 107,
      name: '2',
      builtIn: true,
      builtInCode: 'dataAuthA8',
      category: false,
      parentId: 81,
      parentName: '数据安全等级',
      properties: '{"builtInCode":"dataAuthA8","description":""}',
      order: null,
      catalogId: null,
      associatedTags: null,
      tagGroupId: 1,
    },
    {
      tagId: 84,
      name: 'L3-普通数据',
      builtIn: true,
      builtInCode: 'dataAuthA3',
      category: false,
      parentId: 81,
      parentName: '数据安全等级',
      properties:
        '{"builtInCode":"dataAuthA3","description":"部门内部工作角色可以访问的数据,需要账户系统访问1","css:background-color":"#b8aa62"}',
      order: null,
      catalogId: null,
      associatedTags: null,
      tagGroupId: null,
    },
    {
      tagId: 86,
      name: 'L5-商密数据',
      builtIn: true,
      builtInCode: 'dataAuthA5',
      category: false,
      parentId: 81,
      parentName: '数据安全等级',
      properties:
        '{"builtInCode":"dataAuthA5", "description":"企业合同客户薪资等机密数据,需要CEO特别审批,需要加密", "css:background-color":"#aa3f31","css:color":"#fff"}',
      order: null,
      catalogId: null,
      associatedTags: null,
      tagGroupId: null,
    },
    {
      tagId: 85,
      name: 'L4-敏感数据1',
      builtIn: true,
      builtInCode: 'dataAuthA4',
      category: false,
      parentId: 81,
      parentName: '数据安全等级',
      properties:
        '{"description":"个人敏感数据或企业敏感数据,需要数据安全部门特别审批,需要脱敏","buildInCode":"dataAuthA4","css:color":"#fff","css:background-color":"46585e"}',
      order: null,
      catalogId: null,
      associatedTags: [],
      tagGroupId: null,
    },
    {
      tagId: 106,
      name: 'L2-内部公开2',
      builtIn: true,
      builtInCode: 'dataAuthA7',
      category: false,
      parentId: 81,
      parentName: '数据安全等级',
      properties: '{"builtInCode":"dataAuthA7","description":""}',
      order: null,
      catalogId: null,
      associatedTags: null,
      tagGroupId: 1,
    },
  ],
  dirTypeList: [
    {
      label: '域',
      value: 'domain',
      assetTypes: [],
    },
    {
      label: '主题目录',
      value: 'theme',
      assetTypes: [],
    },
    {
      label: '逻辑数据集',
      value: 'dataSet',
      assetTypes: [
        {
          name: '数据项',
          code: 'dataItems',
        },
      ],
    },
    {
      label: '业务场景',
      value: 'business',
      assetTypes: [
        {
          name: '数据项',
          code: 'dataItems',
        },
        {
          name: '数据集',
          code: 'dataSet',
        },
        {
          name: '数据标准',
          code: 'dataStandard',
        },
        {
          name: '指标',
          code: 'dataIndex',
        },
        {
          name: '报表',
          code: 'report',
        },
        {
          name: '文件',
          code: 'file',
        },
      ],
    },
  ],
  approverList: [
    {
      label: '张三',
      value: 'zhangsan',
    },
    {
      label: '李四',
      value: 'lisi',
    },
  ],
  assetsData,
  propsData: {
    ownship: '产品部',
    steward: 'admin',
    topUsers: [
      {
        username: 'admin',
        firstName: 'Super User',
        visitCount: 539,
      },
      {
        username: 'gujiameng',
        firstName: '顾佳萌',
        visitCount: 39,
      },
      {
        username: 'ghl',
        firstName: 'huiliang gao',
        visitCount: 5,
      },
    ],
    extendProps: {
      回归test: [
        {
          key: 'table_字符属性',
          value: {
            id: 1,
            typeId: null,
            name: 'table_字符属性',
            order: 0,
            desc: '',
            catalog: '回归test',
            type: 'STRING',
            typeData: null,
            lastModification: null,
            modifier: null,
            value: null,
            valId: null,
            add: true,
            mergeNameAndVal: 'table_字符属性:null',
            emptyValue: '',
            nameAndTypeId: 'table_字符属性^null',
          },
          tag: false,
        },
        {
          key: 'table_数值属性',
          value: {
            id: 2,
            typeId: null,
            name: 'table_数值属性',
            order: 0,
            desc: '',
            catalog: '回归test',
            type: 'NUM',
            typeData: null,
            lastModification: null,
            modifier: null,
            value: null,
            valId: null,
            add: true,
            mergeNameAndVal: 'table_数值属性:null',
            emptyValue: '',
            nameAndTypeId: 'table_数值属性^null',
          },
          tag: false,
        },
        {
          key: 'table_布尔属性',
          value: {
            id: 3,
            typeId: null,
            name: 'table_布尔属性',
            order: 0,
            desc: '',
            catalog: '回归test',
            type: 'BOOL',
            typeData: null,
            lastModification: null,
            modifier: null,
            value: null,
            valId: null,
            add: true,
            mergeNameAndVal: 'table_布尔属性:null',
            emptyValue: '',
            nameAndTypeId: 'table_布尔属性^null',
          },
          tag: false,
        },
        {
          key: 'table_枚举属性',
          value: {
            id: 4,
            typeId: null,
            name: 'table_枚举属性',
            order: 0,
            desc: '',
            catalog: '回归test',
            type: 'ENUM',
            typeData: 'a\nb\nc\nd',
            lastModification: null,
            modifier: null,
            value: null,
            valId: null,
            add: true,
            mergeNameAndVal: 'table_枚举属性:null',
            emptyValue: '',
            nameAndTypeId: 'table_枚举属性^null',
          },
          tag: false,
        },
      ],
      佳萌分组: [
        {
          key: '佳萌系统中添加表属性',
          value: {
            id: 15,
            typeId: null,
            name: '佳萌系统中添加表属性',
            order: 0,
            desc: '',
            catalog: '佳萌分组',
            type: 'STRING',
            typeData: null,
            lastModification: null,
            modifier: null,
            value: null,
            valId: null,
            add: true,
            mergeNameAndVal: '佳萌系统中添加表属性:null',
            emptyValue: '',
            nameAndTypeId: '佳萌系统中添加表属性^null',
          },
          tag: false,
        },
      ],
    },
    generalSetting: {
      status: '审核中',
      type: '业务域',
      approver: 'admin',
      authority: '管理员（可编辑，可查看）',
      securityLevel: 'L1-公开数据',
    },
    systemSetting: {
      creator: 'admin',
      createTime: '2022.04.07',
      publishTime: '2022.04.07',
    },
  },
  statisticsData: {
    desc: '暂无信息',
    assetsList: [
      {
        id: 'a1',
        name: '数据表',
        type: 'table',
        count: 200,
      },
      {
        id: 'a2',
        name: '数据项',
        type: 'items',
        count: 200,
      },
      {
        id: 'a3',
        name: '数据标准',
        type: 'standard',
        count: 200,
      },
      {
        id: 'a7',
        name: '数据服务',
        type: 'service',
        count: 200,
      },
      {
        id: 'a4',
        name: '指标',
        type: 'index',
        count: 200,
      },
      {
        id: 'a5',
        name: '报表',
        type: 'report',
        count: 200,
      },
      {
        id: 'a6',
        name: '文件',
        type: 'file',
        count: 200,
      },
    ],
    parentList: [
      {
        id: 'p1',
        name: '零售业务',
        count: 500,
        owner: '产品部',
        date: '2022.05.07',
        status: 2,
        star: 5,
      },
    ],
    childList: [
      {
        id: 'c1',
        name: 'VIP客户',
        count: 340,
        owner: '产品部',
        date: '2022.05.07',
        status: 2,
        star: 4,
      },
      {
        id: 'c2',
        name: '普通用户',
        count: 570,
        owner: '产品部',
        date: '2022.05.07',
        status: 1,
        star: 5,
      },
      {
        id: 'c3',
        name: '临时用户',
        count: 500,
        owner: '产品部',
        date: '2022.05.07',
        status: 0,
        star: 3,
      },
      {
        id: 'c4',
        name: '临时用户',
        count: 500,
        owner: '产品部',
        date: '2022.05.07',
        status: 1,
        star: 5,
      },
      {
        id: 'c5',
        name: '临时用户',
        count: 500,
        owner: '产品部',
        date: '2022.05.07',
        status: 2,
        star: 1,
      },
    ],
  },
  assetsTableColumns: {
    dataItems: [
      {
        prop: 'name',
        label: '数据项名称',
        minWidth: '150px',
      },
      {
        prop: 'type',
        label: '数据类型',
        minWidth: '120px',
      },
      {
        prop: 'standard',
        label: '数据标准',
        minWidth: '120px',
      },
      {
        prop: 'tags',
        label: '标签',
        minWidth: '120px',
      },
      {
        prop: 'remark',
        label: '备注',
        minWidth: '120px',
      },
    ],
    dataSet: [
      {
        prop: 'name',
        label: '表名称',
        minWidth: '150px',
      },
      {
        prop: 'system',
        label: '业务系统',
        minWidth: '120px',
      },
      {
        prop: 'dataSource',
        label: '数据源',
        minWidth: '120px',
      },
      {
        prop: 'createTime',
        label: '创建时间',
        minWidth: '120px',
      },
    ],
    dataStandard: [
      {
        prop: 'name',
        label: '标准名称',
        minWidth: '150px',
      },
      {
        prop: 'code',
        label: '标准编码',
        minWidth: '120px',
      },
      {
        prop: 'theme',
        label: '标准主题',
        minWidth: '120px',
      },
      {
        prop: 'department',
        label: '业务定义部门',
        minWidth: '120px',
      },
    ],
    dataIndex: [
      {
        prop: 'name',
        label: '指标名称',
        minWidth: '150px',
      },
      {
        prop: 'code',
        label: '指标编码',
        minWidth: '120px',
      },
      {
        prop: 'measure',
        label: '度量名称',
        minWidth: '120px',
      },
      {
        prop: 'type',
        label: '指标类型',
        minWidth: '120px',
      },
    ],
    report: [
      {
        prop: 'code',
        label: '报表编号',
        minWidth: '120px',
      },
      {
        prop: 'name',
        label: '报表名称',
        minWidth: '200px',
      },
      {
        prop: 'type',
        label: '报表类型',
        minWidth: '120px',
      },
      {
        prop: 'director',
        label: '负责人',
        minWidth: '120px',
      },
      {
        prop: 'createTime',
        label: '创建时间',
        minWidth: '120px',
      },
    ],
    file: [
      {
        prop: 'name',
        label: '文件名称',
        minWidth: '150px',
      },
      {
        prop: 'type',
        label: '文件类型',
        minWidth: '120px',
      },
      {
        prop: 'size',
        label: '文件大小',
        minWidth: '120px',
      },
      {
        prop: 'createTime',
        label: '创建时间',
        minWidth: '120px',
      },
    ],
  },
  reportTypeOptions: [
    {
      label: '报表',
      value: 'type1',
    },
    {
      label: '多维分析',
      value: 'type2',
    },
  ],
  fileTypeOptions: [
    {
      label: 'LIC',
      value: 'LIC',
    },
    {
      label: 'JPG',
      value: 'JPG',
    },
    {
      label: 'EXE',
      value: 'EXE',
    },
  ],
  assetsListView: [
    {
      domainId: '7b38aa4e84bc443a93d17ff9f10b1b76',
      code: 'customer_024',
      name: '居住状况代码',
      alias: 'BLDG_STAT',
      abbr: 'BLDG_STAT',
      description: '记录个人客户的居住状况，如：“自置”、“按揭”、“租房”等。',
      categoryId: 1,
      folderId: 101,
      domainState: 'A',
      udpValues: ['', '', ''],
      typeId: 80010066,
      clickCount: 1,
      vote: 0,
    },
    {
      domainId: '5325babb13af49a29a30fa559591f1ca',
      code: 'aaa',
      name: 'aaa',
      alias: 'aa',
      abbr: 'aa',
      description: 'aaa',
      categoryId: 1,
      folderId: 130,
      domainState: 'A',
      udpValues: ['', '', '', '', '', '', '', '', 'aaa'],
      typeId: 80010066,
      clickCount: 6,
      vote: 0,
    },
    {
      domainId: 'db8aac6edd2c45bc9ad00e95c8f4e428',
      code: 'gjm_标准引用代码\t gjm_标准引用代码\t gjm_标准引用代码\t gjm_标准引用代码\t gjm_标准引用代码',
      name: 'gjm_标准引用代码\t gjm_标准引用代码',
      alias: 'gjm_标准引用代码',
      abbr: 'gjm_标准引用代码',
      description: 'gjm_标准引用代码',
      categoryId: 1,
      folderId: 119,
      domainState: 'A',
      udpValues: ['', '', '', '', '是'],
      typeId: 80010066,
      clickCount: 6,
      vote: 0,
    },
    {
      domainId: '15623e4e76894a6687f2deed178a3103',
      code: 'qqy002',
      name: 'qqy绑定代码001',
      alias: 'qqy002',
      abbr: 'qqy002',
      description: 'qqy002',
      categoryId: 1,
      folderId: 152,
      domainState: 'A',
      udpValues: ['', '', '', '', '', '', '11'],
      typeId: 80010066,
      clickCount: 11,
      vote: 0,
    },
    {
      domainId: '09c1cfb528ea48c290d23dd48ddbea95',
      code: 'dc_264',
      name: '身份证号',
      alias: 'sfzh',
      abbr: 'sfzh',
      description: '23',
      categoryId: 1,
      folderId: 167,
      domainState: 'A',
      udpValues: ['', '', '', '', '', '', 'a', '', '23'],
      typeId: 80010066,
      clickCount: 12,
      vote: 0,
    },
    {
      domainId: 'e82914fffde14c15a95c9198fd06a3cb',
      code: 'test_lsssas',
      name: 'test_lsssas',
      alias: 'test_lsssas',
      abbr: 'test_lsssas',
      description: 'test_lsssas',
      categoryId: 1,
      folderId: 101,
      domainState: 'A',
      udpValues: ['', '', ''],
      typeId: 80010066,
      clickCount: 1,
      vote: 0,
    },
    {
      domainId: '50beafd023e4444caa294c1d3db07aca',
      code: 'kuozhanshuxing',
      name: '导入扩展属性-已发布',
      alias: 'englishname',
      abbr: '23',
      description: '23',
      categoryId: 1,
      folderId: 115,
      domainState: 'A',
      udpValues: [
        '导入扩展属性',
        '导入扩展属性',
        '导入扩展属性',
        '导入扩展属性',
        '导入扩展属性',
        '导入扩展属性',
        '导入1',
        'a',
        '100万',
      ],
      typeId: 80010066,
      clickCount: 90,
      vote: 4,
    },
    {
      domainId: 'fc769f3f6f3c41d79d7d5143d7a1fc67',
      code: 'customer_023',
      name: '婚姻状况',
      alias: 'MARITAL_STAT',
      abbr: 'MARITAL_STAT',
      description: '记录个人客户的婚姻状况，如“未婚”、“已婚”等。',
      categoryId: 1,
      folderId: 101,
      domainState: 'A',
      udpValues: ['', '', ''],
      typeId: 80010066,
      clickCount: 2,
      vote: 0,
    },
    {
      domainId: '40413dc23a4b43dfa220505ae25f4bf4',
      code: 'customer_031',
      name: '员工标志',
      alias: 'FI_EMP_FLAG',
      abbr: 'FI_EMP_FLAG',
      description:
        '记录个人客户是否是我行员工的标志说明，遵循标志的填写规则，1是0非。',
      categoryId: 1,
      folderId: 101,
      domainState: 'A',
      typeId: 80010066,
      clickCount: 7,
      vote: 0,
    },
    {
      domainId: 'f8850aa1a2c84a469674bb8038af2fd9',
      code: 'bitian',
      name: '必填校验',
      alias: '23424',
      abbr: 'colour',
      description: '43324',
      categoryId: 1,
      folderId: 119,
      domainState: 'A',
      udpValues: ['', '', '', '', '', '', '', 'b', '', '22'],
      typeId: 80010066,
      clickCount: 14,
      vote: 0,
    },
  ],
  suggestionRes: {
    took: 15,
    timed_out: false,
    _shards: {
      total: 6,
      successful: 6,
      skipped: 0,
      failed: 0,
    },
    hits: {
      total: {
        value: 679,
        relation: 'eq',
      },
      max_score: null,
      hits: [],
    },
    aggregations: {
      'lterms#group_by_type': {
        doc_count_error_upper_bound: 0,
        sum_other_doc_count: 0,
        buckets: [
          {
            key: 80000004,
            doc_count: 655,
            'top_hits#hits_typeId_tops': {
              hits: {
                total: {
                  value: 655,
                  relation: 'eq',
                },
                max_score: 2.0,
                hits: [
                  {
                    _index: 'ddc_dataobject_liuqiang4',
                    _type: '_doc',
                    _id: '4094163',
                    _score: 2.0,
                    _source: {
                      id: 4094163,
                      objectId: 470409,
                      modelId: 470319,
                      categoryId: 23,
                      schema: 'SYSTEM',
                      typeId: 80000004,
                      description:
                        'Summary management rewrite eligibility information',
                      name: 'MVIEW$_ADV_ELIGIBLE',
                      alias: 'Summary management rewrite eligi',
                      parentName: 'd-192.168.1.131-20220714173807',
                      parentAlias: null,
                      modelName: 'd-192.168.1.131-20220714173807',
                      clickCount: 0,
                      endVer: null,
                      creationTime: '2022-08-12T14:51:09.698000000Z',
                    },
                  },
                  {
                    _index: 'ddc_dataobject_liuqiang4',
                    _type: '_doc',
                    _id: '4094172',
                    _score: 2.0,
                    _source: {
                      id: 4094172,
                      objectId: 470418,
                      modelId: 470319,
                      categoryId: 23,
                      schema: 'SYSTEM',
                      typeId: 80000004,
                      description: null,
                      name: 'MVIEW$_ADV_LEVEL',
                      alias: 'Level definition',
                      parentName: 'd-192.168.1.131-20220714173807',
                      parentAlias: null,
                      modelName: 'd-192.168.1.131-20220714173807',
                      clickCount: 0,
                      endVer: null,
                      creationTime: '2022-08-12T14:51:11.047000000Z',
                    },
                  },
                  {
                    _index: 'ddc_dataobject_liuqiang4',
                    _type: '_doc',
                    _id: '4094181',
                    _score: 2.0,
                    _source: {
                      id: 4094181,
                      objectId: 470427,
                      modelId: 470319,
                      categoryId: 23,
                      schema: 'SYSTEM',
                      typeId: 80000004,
                      description: 'Temporary table for workload collections',
                      name: 'MVIEW$_ADV_SQLDEPEND',
                      alias: 'Temporary table for workload col',
                      parentName: 'd-192.168.1.131-20220714173807',
                      parentAlias: null,
                      modelName: 'd-192.168.1.131-20220714173807',
                      clickCount: 0,
                      endVer: null,
                      creationTime: '2022-08-12T14:51:12.149000000Z',
                    },
                  },
                  {
                    _index: 'ddc_dataobject_liuqiang4',
                    _type: '_doc',
                    _id: '4094190',
                    _score: 2.0,
                    _source: {
                      id: 4094190,
                      objectId: 470440,
                      modelId: 470319,
                      categoryId: 23,
                      schema: 'SYSTEM',
                      typeId: 80000004,
                      description: 'Repcat processing exceptions table.',
                      name: 'REPCAT$_EXCEPTIONS',
                      alias: 'Repcat processing exceptions tab',
                      parentName: 'd-192.168.1.131-20220714173807',
                      parentAlias: null,
                      modelName: 'd-192.168.1.131-20220714173807',
                      clickCount: 0,
                      endVer: null,
                      creationTime: '2022-08-12T14:51:17.083000000Z',
                    },
                  },
                  {
                    _index: 'ddc_dataobject_liuqiang4',
                    _type: '_doc',
                    _id: '4094208',
                    _score: 2.0,
                    _source: {
                      id: 4094208,
                      objectId: 470460,
                      modelId: 470319,
                      categoryId: 23,
                      schema: 'SYSTEM',
                      typeId: 80000004,
                      description: null,
                      name: 'REPCAT$_REPSCHEMA',
                      alias: 'N-way replication information',
                      parentName: 'd-192.168.1.131-20220714173807',
                      parentAlias: null,
                      modelName: 'd-192.168.1.131-20220714173807',
                      clickCount: 0,
                      endVer: null,
                      creationTime: '2022-08-12T14:51:23.759000000Z',
                    },
                  },
                ],
              },
            },
          },
          {
            key: 80010066,
            doc_count: 12,
            'top_hits#hits_typeId_tops': {
              hits: {
                total: {
                  value: 12,
                  relation: 'eq',
                },
                max_score: 2.5296774,
                hits: [
                  {
                    _index: 'ddc_domain_liuqiang4',
                    _type: '_doc',
                    _id: 'b814f25b03644caaa871bf27b7063817',
                    _score: 2.5296774,
                    _source: {
                      domainId: 'b814f25b03644caaa871bf27b7063817',
                      code: '新增greenplum',
                      name: 'DAMgreen plum',
                      alias: 'AAA',
                      abbr: 'SSS',
                      description: 'JJJ',
                      categoryId: 2,
                      folderId: 116,
                      domainState: 'A',
                      udpValues: ['FFF', 'GGG', 'HHH', 'DDD'],
                      typeId: 80010066,
                      clickCount: 30,
                      vote: 0.0,
                    },
                  },
                  {
                    _index: 'ddc_domain_liuqiang4',
                    _type: '_doc',
                    _id: '25bb9ace08e5492fbc9ed6c51a33d734',
                    _score: 2.5296774,
                    _source: {
                      domainId: '25bb9ace08e5492fbc9ed6c51a33d734',
                      code: 'lxtCD0006',
                      name: 'lxt受益比例',
                      alias: 'Benefit Ratio',
                      abbr: 'BR',
                      description: '受益比例',
                      categoryId: 1,
                      folderId: 183,
                      domainState: 'A',
                      udpValues: [
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                        '',
                      ],
                      typeId: 80010066,
                      clickCount: 3,
                      path: ['/0/1/2'],
                      vote: 0.0,
                    },
                  },
                  {
                    _index: 'ddc_domain_liuqiang4',
                    _type: '_doc',
                    _id: '294327453c96456ba941b150057605c5',
                    _score: 2.5296774,
                    _source: {
                      domainId: '294327453c96456ba941b150057605c5',
                      code: 'xxxxxx677',
                      name: 'testx',
                      alias: 'test xxx',
                      abbr: 'testx',
                      description: null,
                      categoryId: 1,
                      folderId: 303,
                      domainState: 'A',
                      typeId: 80010066,
                      clickCount: 1,
                      vote: 0.0,
                    },
                  },
                  {
                    _index: 'ddc_domain_liuqiang4',
                    _type: '_doc',
                    _id: '7731c3f7457e4ed694ef4f2788ae5273',
                    _score: 2.5296774,
                    _source: {
                      domainId: '7731c3f7457e4ed694ef4f2788ae5273',
                      code: 'asdfgnb',
                      name: '11123421321',
                      alias: '122 23421321',
                      abbr: '122_23421321',
                      description: null,
                      categoryId: 1,
                      folderId: 310,
                      domainState: 'A',
                      typeId: 80010066,
                      clickCount: 1,
                      vote: 0.0,
                    },
                  },
                  {
                    _index: 'ddc_domain_liuqiang4',
                    _type: '_doc',
                    _id: 'e21ae666a807432486ab2ebca940c217',
                    _score: 2.5296774,
                    _source: {
                      domainId: 'e21ae666a807432486ab2ebca940c217',
                      code: '222233333',
                      name: '11111',
                      alias: '122 2222',
                      abbr: '122_22',
                      description: null,
                      categoryId: 1,
                      folderId: 304,
                      domainState: 'A',
                      typeId: 80010066,
                      clickCount: 1,
                      vote: 0.0,
                    },
                  },
                ],
              },
            },
          },
          {
            key: 80010098,
            doc_count: 10,
            'top_hits#hits_typeId_tops': {
              hits: {
                total: {
                  value: 10,
                  relation: 'eq',
                },
                max_score: 1.562826,
                hits: [
                  {
                    _index: 'ddc_stdcode_liuqiang4',
                    _type: '_doc',
                    _id: 'CD0007',
                    _score: 1.562826,
                    _source: {
                      code: 'CD0007',
                      name: '国家代码',
                      alias: 'Country Code',
                      datasetName: '基础代码',
                      state: 'A',
                      comment: '',
                      typeId: 80010098,
                      codeValueName: 'ARE',
                      clickCount: 0,
                    },
                  },
                  {
                    _index: 'ddc_stdcode_liuqiang4',
                    _type: '_doc',
                    _id: 'CD0009',
                    _score: 1.562826,
                    _source: {
                      code: 'CD0009',
                      name: '国家代码',
                      alias: 'Country Code',
                      datasetName: '基础代码',
                      state: 'A',
                      comment: '',
                      typeId: 80010098,
                      codeValueName: 'OMN',
                      clickCount: 0,
                    },
                  },
                  {
                    _index: 'ddc_stdcode_liuqiang4',
                    _type: '_doc',
                    _id: 'CD0011',
                    _score: 1.562826,
                    _source: {
                      code: 'CD0011',
                      name: '国家代码',
                      alias: 'Country Code',
                      datasetName: '基础代码',
                      state: 'A',
                      comment: '',
                      typeId: 80010098,
                      codeValueName: 'EGY',
                      clickCount: 0,
                    },
                  },
                  {
                    _index: 'ddc_stdcode_liuqiang4',
                    _type: '_doc',
                    _id: 'CD0008',
                    _score: 1.562826,
                    _source: {
                      code: 'CD0008',
                      name: '国家代码',
                      alias: 'Country Code',
                      datasetName: '基础代码',
                      state: 'A',
                      comment: '',
                      typeId: 80010098,
                      codeValueName: 'ABW',
                      clickCount: 0,
                    },
                  },
                  {
                    _index: 'ddc_stdcode_liuqiang4',
                    _type: '_doc',
                    _id: 'CD0004',
                    _score: 1.562826,
                    _source: {
                      code: 'CD0004',
                      name: '国家代码',
                      alias: 'Country Code',
                      datasetName: '基础代码',
                      state: 'A',
                      comment: '',
                      typeId: 80010098,
                      codeValueName: 'DZA',
                      clickCount: 0,
                    },
                  },
                ],
              },
            },
          },
          {
            key: 82800002,
            doc_count: 1,
            'top_hits#hits_typeId_tops': {
              hits: {
                total: {
                  value: 1,
                  relation: 'eq',
                },
                max_score: 1.0,
                hits: [
                  {
                    _index: 'ddc_report_liuqiang4',
                    _type: '_doc',
                    _id: '130',
                    _score: 1.0,
                    _source: {
                      id: 130,
                      code: 'RP_0000130',
                      name: 'GJM_TEST ',
                      description: null,
                      thumbnailFileId: null,
                      createTime: '2022-06-27T16:00:00.000000000Z',
                      dataReportType: 'Analysis',
                      owner: '顾佳萌',
                      url: null,
                      typeId: 82800002,
                      clickCount: 2,
                      columns: [],
                      metrics: [],
                      vote: 0.0,
                    },
                  },
                ],
              },
            },
          },
          {
            key: 82800008,
            doc_count: 1,
            'top_hits#hits_typeId_tops': {
              hits: {
                total: {
                  value: 1,
                  relation: 'eq',
                },
                max_score: 1.0,
                hits: [
                  {
                    _index: 'ddc_share_file_liuqiang4',
                    _type: '_doc',
                    _id: '7',
                    _score: 1.0,
                    _source: {
                      id: 7,
                      name: '顾佳萌测试 修改、创建时间11.ppt',
                      filePath: '\\\\192.168.1.123\\nas\\员工共享\\gjm',
                      fileType: 'ppt',
                      modelId: 362342,
                      categoryId: 4,
                      typeId: 82800008,
                      clickCount: 2,
                      tagIds: [],
                    },
                  },
                ],
              },
            },
          },
        ],
      },
    },
  },
}
