enum GraphType {
  TABLE_ONLY,
  TABLE_AND_COLUMN,
  SCHEMA_AND_TABLE,
  SCHEMA_AND_TABLE_AND_COLUMN,
  CATEGORY_AND_TABLE,
  CATEGORY_AND_TABLE_AND_COLUMN,
  CATEGORY_AND_SCHEMA_AND_TABLE,
  CATEGORY_AND_SCHEMA_AND_TABLE_AND_COLUMN,
  MODEL_AND_TABLE,
  MODEL_AND_TABLE_AND_COLUMN
}
export default GraphType
